import uiScriptLocale

BUTTONS_COUNT = 9
BOARD_WIDTH = 37
BOARD_HEIGHT = (38 * BUTTONS_COUNT)

window = {
	"name" : "InventoryMenuWindow",
	"x" : 0,
	"y" : 0,
	"style" : ("movable", "float",),
	"width" : BOARD_WIDTH,
	"height" : BOARD_HEIGHT,
	"children" :
	(
		{
			"name" : "board",
			"type" : "bar",
			"x" : 0,
			"y" : 0,
			"width" : BOARD_WIDTH,
			"height" : BOARD_HEIGHT,
			"color" : 0x00000000,
			"children" : 
			(
				{
					"name" : "button1",
					"type" : "button",
					"x" : 5,
					"y" : 0,
					"tooltip_text" : uiScriptLocale.EXTRA_INVENTORY,
					"tooltip_x" : -70,
					"tooltip_y" : 10,
					"default_image" : "new/q2.png",
					"over_image" : "new/q1.png",
					"down_image" : "new/q2.png",
				},	
				{
					"name" : "button2",
					"type" : "button",
					"x" : 5,
					"y" : BOARD_WIDTH,
					"tooltip_text" : uiScriptLocale.SWITCH_BOT,
					"tooltip_x" : -59,
					"tooltip_y" : 10,
					"default_image" : "new/s1.png",
					"over_image" : "new/s2.png",
					"down_image" : "new/s1.png",
				},
				{
					"name" : "button3",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 2),
					"tooltip_text" : uiScriptLocale.CLASSIFICA_GILDA,
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/rank_normal.png",
					"over_image" : "new/rank_hover.png",
					"down_image" : "new/rank_down.png",
				},
				{
					"name" : "button4",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 3),
					"tooltip_text" : "Okno Biologa",
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/zub_normal.png",
					"over_image" : "new/zub_hover.png",
					"down_image" : "new/zub_normal.png",
				},
				{
					"name" : "button5",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 4),
					"tooltip_text" : "Dungeon Panel",
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/d1.png",
					"over_image" : "new/d2.png",
					"down_image" : "new/d1.png",
				},	
				{
					"name" : "button6",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 5),
					"tooltip_text" : "Wiki",
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/w_normal.png",
					"over_image" : "new/w_hover.png",
					"down_image" : "new/w_down.png",
				},
				{
					"name" : "button7",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 6),
					"tooltip_text" : "Batlle Pass",
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/b1.png",
					"over_image" : "new/b2.png",
					"down_image" : "new/b1.png",
				},
                {
					"name" : "button8",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 7),
					"tooltip_text" : "Teleport[TAB]",
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/p1.png",
					"over_image" : "new/p2.png",
					"down_image" : "new/p1.png",
				},
                {
					"name" : "button9",
					"type" : "button",
					"x" : 5,
					"y" : (BOARD_WIDTH * 8),
					"tooltip_text" : "Uložení Pozic",
					"tooltip_x" : -67,
					"tooltip_y" : 10,
					"default_image" : "new/n1.png",
					"over_image" : "new/n2.png",
					"down_image" : "new/n1.png",
				},
			),
		},
	),
}
